using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HillmanGroup.API.Models.JDEEntities
{
    public partial class F0411z1
    {
        public string Vledus { get; set; }
        public string Vledty { get; set; }
        public decimal? Vledsq { get; set; }
        public string Vledtn { get; set; }
        public string Vledct { get; set; }
        public decimal? Vledln { get; set; }
        public string Vledts { get; set; }
        public string Vledft { get; set; }
        public decimal? Vleddt { get; set; }
        public string Vleder { get; set; }
        public decimal? Vleddl { get; set; }
        public string Vledsp { get; set; }
        public string Vledtc { get; set; }
        public string Vledtr { get; set; }
        public string Vledbt { get; set; }
        public string Vledgl { get; set; }
        public string Vleddh { get; set; }
        public decimal? Vledan { get; set; }
        public string Vlkco { get; set; }
        public decimal? Vldoc { get; set; }
        public string Vldct { get; set; }
        public string Vlsfx { get; set; }
        public decimal? Vlsfxe { get; set; }
        public string Vldcta { get; set; }
        public decimal? Vlan8 { get; set; }
        public decimal? Vlpye { get; set; }
        public decimal? Vlsnto { get; set; }
        public decimal? Vldivj { get; set; }
        public decimal? Vldsvj { get; set; }
        public decimal? Vlddj { get; set; }
        public decimal? Vlddnj { get; set; }
        public decimal? Vldgj { get; set; }
        public decimal? Vlfy { get; set; }
        public decimal? Vlctry { get; set; }
        public decimal? Vlpn { get; set; }
        public string Vlco { get; set; }
        public decimal? Vlicu { get; set; }
        public string Vlicut { get; set; }
        public decimal? Vldicj { get; set; }
        public string Vlbalj { get; set; }
        public string Vlpst { get; set; }
        public decimal? Vlag { get; set; }
        public decimal? Vlaap { get; set; }
        public decimal? Vladsc { get; set; }
        public decimal? Vladsa { get; set; }
        public decimal? Vlatxa { get; set; }
        public decimal? Vlatxn { get; set; }
        public decimal? Vlstam { get; set; }
        public string Vltxa1 { get; set; }
        public string Vlexr1 { get; set; }
        public string Vlcrrm { get; set; }
        public string Vlcrcd { get; set; }
        public decimal? Vlcrr { get; set; }
        public decimal? Vlacr { get; set; }
        public decimal? Vlfap { get; set; }
        public decimal? Vlcds { get; set; }
        public decimal? Vlcdsa { get; set; }
        public decimal? Vlctxa { get; set; }
        public decimal? Vlctxn { get; set; }
        public decimal? Vlctam { get; set; }
        public string Vlglc { get; set; }
        public string Vlglba { get; set; }
        public string Vlpost { get; set; }
        public string Vlam { get; set; }
        public string Vlaid2 { get; set; }
        public string Vlmcu { get; set; }
        public string Vlobj { get; set; }
        public string Vlsub { get; set; }
        public string Vlsblt { get; set; }
        public string Vlsbl { get; set; }
        public string Vlbaid { get; set; }
        public string Vlptc { get; set; }
        public string Vlvod { get; set; }
        public string Vlokco { get; set; }
        public string Vlodct { get; set; }
        public decimal? Vlodoc { get; set; }
        public string Vlosfx { get; set; }
        public string Vlcrc { get; set; }
        public string Vlvinv { get; set; }
        public string Vlpkco { get; set; }
        public string Vlpo { get; set; }
        public string Vlpdct { get; set; }
        public decimal? Vllnid { get; set; }
        public string Vlsfxo { get; set; }
        public decimal? Vlopsq { get; set; }
        public string Vlvr01 { get; set; }
        public string Vlunit { get; set; }
        public string Vlmcu2 { get; set; }
        public string Vlrmk { get; set; }
        public string Vlrf { get; set; }
        public decimal? Vldrf { get; set; }
        public string Vlctl { get; set; }
        public string Vlfnlp { get; set; }
        public decimal? Vlu { get; set; }
        public string Vlum { get; set; }
        public string Vlpyin { get; set; }
        public string Vltxa3 { get; set; }
        public string Vlexr3 { get; set; }
        public string Vlrp1 { get; set; }
        public string Vlrp2 { get; set; }
        public string Vlrp3 { get; set; }
        public string Vlac07 { get; set; }
        public string Vltnn { get; set; }
        public string Vldmcd { get; set; }
        public decimal? Vlitm { get; set; }
        public decimal? Vlhcrr { get; set; }
        public decimal? Vlhdgj { get; set; }
        public string Vlurc1 { get; set; }
        public decimal? Vlurdt { get; set; }
        public decimal? Vlurat { get; set; }
        public decimal? Vlurab { get; set; }
        public string Vlurrf { get; set; }
        public string Vltorg { get; set; }
        public string Vluser { get; set; }
        public string Vlpid { get; set; }
        public decimal? Vlupmj { get; set; }
        public decimal? Vlupmt { get; set; }
        public string Vljobn { get; set; }
        public decimal? Vldim { get; set; }
        public decimal? Vldid { get; set; }
        public decimal? Vldiy { get; set; }
        public decimal? Vldi { get; set; }
        public decimal? Vldsvm { get; set; }
        public decimal? Vldsvd { get; set; }
        public decimal? Vldsvy { get; set; }
        public decimal? Vldsv { get; set; }
        public decimal? Vlddm { get; set; }
        public decimal? Vlddd { get; set; }
        public decimal? Vlddy { get; set; }
        public decimal? Vldd { get; set; }
        public decimal? Vlddnm { get; set; }
        public decimal? Vlddnd { get; set; }
        public decimal? Vlddny { get; set; }
        public decimal? Vlddn { get; set; }
        public decimal? Vldgm { get; set; }
        public decimal? Vldgd { get; set; }
        public decimal? Vldgy { get; set; }
        public decimal? Vldg { get; set; }
        public decimal? Vldicm { get; set; }
        public decimal? Vldicd { get; set; }
        public decimal? Vldicy { get; set; }
        public decimal? Vldic { get; set; }
        public decimal? Vlhdgm { get; set; }
        public decimal? Vlhdgd { get; set; }
        public decimal? Vlhdgy { get; set; }
        public decimal? Vlhdg { get; set; }
        public decimal? Vldocm { get; set; }
        public string Vltnst { get; set; }
        public string Vlyc01 { get; set; }
        public string Vlyc02 { get; set; }
        public string Vlyc03 { get; set; }
        public string Vlyc04 { get; set; }
        public string Vlyc05 { get; set; }
        public string Vlyc06 { get; set; }
        public string Vlyc07 { get; set; }
        public string Vlyc08 { get; set; }
        public string Vlyc09 { get; set; }
        public string Vlyc10 { get; set; }
        public string Vldtxs { get; set; }
        public string Vlbcrc { get; set; }
        public decimal? Vlatad { get; set; }
        public decimal? Vlctad { get; set; }
        public decimal? Vlnrta { get; set; }
        public decimal? Vlfnrt { get; set; }
        public string Vltaxp { get; set; }
        public string Vlprgf { get; set; }
        public string Vlgfl5 { get; set; }
        public string Vlgfl6 { get; set; }
        public decimal? Vlgam1 { get; set; }
        public decimal? Vlgam2 { get; set; }
        public string Vlgen4 { get; set; }
        public string Vlgen5 { get; set; }
        public decimal? Vlwtad { get; set; }
        public decimal? Vlwtaf { get; set; }
        public string Vlsmmf { get; set; }
        public string Vlpywp { get; set; }
        public decimal? Vlpwpg { get; set; }
        public string Vlnetst { get; set; }
    }
}
